name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12

      - name: Install dependencies
        run: npm install
        working-directory: ./Predict.Client

      - name: Build Angular app
        run: |
          npm run build -- --configuration production --base-href "/predict/"
        working-directory: ./Predict.Client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Predict.Client/dist/predict.client
